# Generated by Django 3.1.4 on 2020-12-16 12:28

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='front_cover',
            field=models.ImageField(help_text='Select book front cover', null=True, upload_to=catalog.models.user_directory_path),
        ),
    ]
