# Generated by Django 3.1.4 on 2020-12-16 14:13

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201216_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='front_cover',
            field=models.ImageField(help_text='Select book front cover', max_length=200, null=True, upload_to=catalog.models.user_directory_path),
        ),
    ]
